/**
 * Typed error classes with stable machine codes (FR-DATA-001…006, FR-DR-001…002).
 *
 * Every refusal in this repository surfaces one of these errors so callers and
 * telemetry can branch on `code` — never on prose. All refusals are fail-closed:
 * there is no error class meaning "guess a default instead".
 */

/** Stable machine-readable error codes. Values never change once released. */
export const ErrorCode = {
  // --- identity (FR-DATA-001)
  IDENTITY_CHAIN_ID_INVALID: 'IDENTITY_CHAIN_ID_INVALID',
  IDENTITY_ADDRESS_INVALID: 'IDENTITY_ADDRESS_INVALID',
  IDENTITY_SYMBOL_IS_NOT_AN_IDENTIFIER: 'IDENTITY_SYMBOL_IS_NOT_AN_IDENTIFIER',
  IDENTITY_EQUIVALENCE_UNVERIFIED: 'IDENTITY_EQUIVALENCE_UNVERIFIED',
  IDENTITY_DECIMALS_CONFLICTING: 'IDENTITY_DECIMALS_CONFLICTING',
  IDENTITY_MIGRATION_EDGE_AMBIGUOUS: 'IDENTITY_MIGRATION_EDGE_AMBIGUOUS',
  IDENTITY_MIGRATION_EDGE_CYCLES: 'IDENTITY_MIGRATION_EDGE_CYCLES',
  // --- quantity (FR-DATA-001 / §11.5)
  QUANTITY_DECIMAL_STRING_INVALID: 'QUANTITY_DECIMAL_STRING_INVALID',
  QUANTITY_SCALE_EXCEEDED: 'QUANTITY_SCALE_EXCEEDED',
  QUANTITY_NEGATIVE_UNSUPPORTED: 'QUANTITY_NEGATIVE_UNSUPPORTED',
  // --- observations/revisions (FR-DATA-002 / §13.4)
  OBSERVATION_IMMUTABLE: 'OBSERVATION_IMMUTABLE',
  REVISION_SUPERSEDES_UNKNOWN: 'REVISION_SUPERSEDES_UNKNOWN',
  REVISION_NOT_LATEST: 'REVISION_NOT_LATEST',
  REVISION_BACKDATING_REJECTED: 'REVISION_BACKDATING_REJECTED',
  REORG_COMPENSATION_INVALID: 'REORG_COMPENSATION_INVALID',
  // --- replay/time (FR-DATA-003 / §13.1–13.2, §13.5 watermarks, §13.6)
  REPLAY_BOUNDARY_VIOLATION: 'REPLAY_BOUNDARY_VIOLATION',
  AVAILABILITY_PROVENANCE_UNKNOWN: 'AVAILABILITY_PROVENANCE_UNKNOWN',
  AVAILABLE_AT_INFERRED_FROM_EVENT_AT: 'AVAILABLE_AT_INFERRED_FROM_EVENT_AT',
  BACKFILL_BACKDATING_REJECTED: 'BACKFILL_BACKDATING_REJECTED',
  BACKFILL_AVAILABILITY_PROOF_MISSING: 'BACKFILL_AVAILABILITY_PROOF_MISSING',
  WATERMARK_NON_CONTIGUOUS: 'WATERMARK_NON_CONTIGUOUS',
  WATERMARK_REGRESSION_REJECTED: 'WATERMARK_REGRESSION_REJECTED',
  TIMESTAMP_INVALID: 'TIMESTAMP_INVALID',
  // --- quality (FR-DATA-005 / §13.9)
  QUALITY_CODE_UNKNOWN: 'QUALITY_CODE_UNKNOWN',
  QUALITY_NULL_WITHOUT_CODE: 'QUALITY_NULL_WITHOUT_CODE',
  QUALITY_STATE_REQUIRED: 'QUALITY_STATE_REQUIRED',
  // --- acquisition (§13.8 / AC-242/243)
  ACQUISITION_STATE_UNKNOWN: 'ACQUISITION_STATE_UNKNOWN',
  ACQUISITION_FAILURE_KIND_UNKNOWN: 'ACQUISITION_FAILURE_KIND_UNKNOWN',
  ACQUISITION_WRITE_BEFORE_RETRIEVAL_VIOLATED: 'ACQUISITION_WRITE_BEFORE_RETRIEVAL_VIOLATED',
  ACQUISITION_PROBE_ASSIGNMENT_MISSING: 'ACQUISITION_PROBE_ASSIGNMENT_MISSING',
  // --- features (FR-DATA-004 / AC-244)
  FEATURE_PROVENANCE_INCOMPLETE: 'FEATURE_PROVENANCE_INCOMPLETE',
  FEATURE_ONLINE_OFFLINE_DIVERGENCE: 'FEATURE_ONLINE_OFFLINE_DIVERGENCE',
  // --- sources/independence (FR-DATA-006 / §11.7, INV-008)
  SOURCE_DEPENDENCE_INPUT_INVALID: 'SOURCE_DEPENDENCE_INPUT_INVALID',
  SOURCE_FROZEN_COUNT_IMMUTABLE: 'SOURCE_FROZEN_COUNT_IMMUTABLE',
  // --- checkpoints/gaps (INV-009, AC-263)
  CHECKPOINT_STALE_FENCING_TOKEN: 'CHECKPOINT_STALE_FENCING_TOKEN',
  CHECKPOINT_CURSOR_REGRESSION: 'CHECKPOINT_CURSOR_REGRESSION',
  COLLECTOR_GAP_UNMARKED: 'COLLECTOR_GAP_UNMARKED',
  CANONICAL_EVENT_DUPLICATE: 'CANONICAL_EVENT_DUPLICATE',
  // --- object store / staged commit (ADR-003, §14.8, FR-DR-002)
  OBJECT_HASH_MISMATCH: 'OBJECT_HASH_MISMATCH',
  OBJECT_RIGHTS_METADATA_MISMATCH: 'OBJECT_RIGHTS_METADATA_MISMATCH',
  OBJECT_STAGE_TRANSITION_INVALID: 'OBJECT_STAGE_TRANSITION_INVALID',
  OBJECT_ORPHAN_DETECTED: 'OBJECT_ORPHAN_DETECTED',
  OBJECT_RETENTION_DRIFT: 'OBJECT_RETENTION_DRIFT',
  // --- recovery/drills (FR-DR-001/002, §34)
  RECOVERY_TIER_CEILING_EXCEEDED: 'RECOVERY_TIER_CEILING_EXCEEDED',
  RESTORE_VERIFICATION_FAILED: 'RESTORE_VERIFICATION_FAILED',
  RESTORE_CREDENTIAL_PROVIDER_MISSING: 'RESTORE_CREDENTIAL_PROVIDER_MISSING',
  BACKUP_KEY_MATERIAL_FORBIDDEN: 'BACKUP_KEY_MATERIAL_FORBIDDEN',
  BACKUP_POLICY_INVALID: 'BACKUP_POLICY_INVALID',
  DRILL_INCIDENT_RECORDED: 'DRILL_INCIDENT_RECORDED',
  DRILL_TIMELINE_INVALID: 'DRILL_TIMELINE_INVALID',
  // --- schema migration integrity (substrate under FR-DATA-001…006 / FR-DR-001/002)
  MIGRATION_FILENAME_UNKNOWN: 'MIGRATION_FILENAME_UNKNOWN',
  MIGRATION_FILE_MISSING: 'MIGRATION_FILE_MISSING',
  MIGRATION_OUT_OF_ORDER_REFUSED: 'MIGRATION_OUT_OF_ORDER_REFUSED',
  MIGRATION_CHECKSUM_DRIFT: 'MIGRATION_CHECKSUM_DRIFT',
  MIGRATION_APPLY_ALREADY_RUNNING: 'MIGRATION_APPLY_ALREADY_RUNNING',
  MIGRATION_APPLICATION_FAILED: 'MIGRATION_APPLICATION_FAILED',
  // --- shared tool core vocabularies (FR-CORE-001…008 / §16)
  ACTION_CLASS_UNKNOWN: 'ACTION_CLASS_UNKNOWN',
  WORKLOAD_CLASS_UNKNOWN: 'WORKLOAD_CLASS_UNKNOWN',
  CACHE_OUTCOME_UNKNOWN: 'CACHE_OUTCOME_UNKNOWN',
  QUOTA_MODEL_UNKNOWN: 'QUOTA_MODEL_UNKNOWN',
  RESERVATION_STATE_UNKNOWN: 'RESERVATION_STATE_UNKNOWN',
  BACKPRESSURE_ACTION_UNKNOWN: 'BACKPRESSURE_ACTION_UNKNOWN',
  HOLDER_MODE_UNKNOWN: 'HOLDER_MODE_UNKNOWN',
  TOOL_PROFILE_UNKNOWN: 'TOOL_PROFILE_UNKNOWN',
  FRESHNESS_FIELD_FAMILY_UNKNOWN: 'FRESHNESS_FIELD_FAMILY_UNKNOWN',
  PIPELINE_STAGE_UNKNOWN: 'PIPELINE_STAGE_UNKNOWN',
  TOOL_DEFINITION_PROHIBITED: 'TOOL_DEFINITION_PROHIBITED',
  REGISTRY_ENTRY_UNKNOWN: 'REGISTRY_ENTRY_UNKNOWN',
  SEMANTIC_CACHE_FORBIDDEN: 'SEMANTIC_CACHE_FORBIDDEN',
  FRESHNESS_POLICY_INVALID: 'FRESHNESS_POLICY_INVALID',
  TOOL_DEFINITION_DUPLICATE_HASH: 'TOOL_DEFINITION_DUPLICATE_HASH',
  PIPELINE_STAGE_ORDER_VIOLATED: 'PIPELINE_STAGE_ORDER_VIOLATED',
  AUTHORIZATION_REFUSED: 'AUTHORIZATION_REFUSED',
  AUTHENTICATION_REFUSED: 'AUTHENTICATION_REFUSED',
  INPUT_SCHEMA_INVALID: 'INPUT_SCHEMA_INVALID',
  LEASE_FENCING_TOKEN_STALE: 'LEASE_FENCING_TOKEN_STALE',
  LICENSE_POLICY_UNVERIFIABLE: 'LICENSE_POLICY_UNVERIFIABLE',
  QUOTA_RESERVATION_TRANSITION_ILLEGAL: 'QUOTA_RESERVATION_TRANSITION_ILLEGAL',
  PROVIDER_RESPONSE_INVALID: 'PROVIDER_RESPONSE_INVALID',
  ENVELOPE_INCOMPLETE: 'ENVELOPE_INCOMPLETE',
  // --- discovery coverage and claim honesty (FR-DISC-006…014)
  DISC_ENTRY_REASON_UNKNOWN: 'DISC_ENTRY_REASON_UNKNOWN',
  DISC_RIGHTS_BASIS_UNKNOWN: 'DISC_RIGHTS_BASIS_UNKNOWN',
  DISC_MANIPULATION_POLICY_UNKNOWN: 'DISC_MANIPULATION_POLICY_UNKNOWN',
  DISC_CLAIM_BASIS_UNKNOWN: 'DISC_CLAIM_BASIS_UNKNOWN',
  DISC_CONSTRAINT_KIND_UNKNOWN: 'DISC_CONSTRAINT_KIND_UNKNOWN',
  DISC_CONSTRAINT_EFFECT_UNKNOWN: 'DISC_CONSTRAINT_EFFECT_UNKNOWN',
  DISC_CHAIN_ACCESS_PURPOSE_UNKNOWN: 'DISC_CHAIN_ACCESS_PURPOSE_UNKNOWN',
  DISC_RECALL_VERDICT_UNKNOWN: 'DISC_RECALL_VERDICT_UNKNOWN',
  DISC_LATENESS_BASIS_UNKNOWN: 'DISC_LATENESS_BASIS_UNKNOWN',
  DISC_CLAIM_LANGUAGE_REFUSED: 'DISC_CLAIM_LANGUAGE_REFUSED',
  DISC_POPULATION_MANIFEST_MISSING: 'DISC_POPULATION_MANIFEST_MISSING',
  DISC_ENTRY_PROVENANCE_MISSING: 'DISC_ENTRY_PROVENANCE_MISSING',
  DISC_POPULATION_RIDER_MISSING: 'DISC_POPULATION_RIDER_MISSING',
  // --- cost, quota, and capacity (FR-COST-001…010)
  COST_CLASS_UNKNOWN: 'COST_CLASS_UNKNOWN',
  RESET_POLICY_KIND_UNKNOWN: 'RESET_POLICY_KIND_UNKNOWN',
  RESERVE_ID_UNKNOWN: 'RESERVE_ID_UNKNOWN',
  RESOURCE_BUDGET_KIND_UNKNOWN: 'RESOURCE_BUDGET_KIND_UNKNOWN',
  COST_MODE_UNKNOWN: 'COST_MODE_UNKNOWN',
  UNKNOWN_COST: 'UNKNOWN_COST',
  PAID_POLICY_INVALID: 'PAID_POLICY_INVALID',
  PLAN_UNVERIFIED: 'PLAN_UNVERIFIED',
  QUOTA_EXHAUSTED: 'QUOTA_EXHAUSTED',
  // --- outcome maturity and evidence integrity (FR-MAT-001…012)
  MAT_HORIZON_UNKNOWN: 'MAT_HORIZON_UNKNOWN',
  MAT_CENSOR_REASON_UNKNOWN: 'MAT_CENSOR_REASON_UNKNOWN',
  MAT_INVALID_REASON_UNKNOWN: 'MAT_INVALID_REASON_UNKNOWN',
  MAT_DISCLOSURE_CLASS_UNKNOWN: 'MAT_DISCLOSURE_CLASS_UNKNOWN',
  MAT_LABEL_FAMILY_UNKNOWN: 'MAT_LABEL_FAMILY_UNKNOWN',
  MAT_EVIDENCE_RESOLUTION_UNKNOWN: 'MAT_EVIDENCE_RESOLUTION_UNKNOWN',
  MAT_SIDE_EFFECT_UNKNOWN: 'MAT_SIDE_EFFECT_UNKNOWN',
  MAT_TRANSITION_ILLEGAL: 'MAT_TRANSITION_ILLEGAL',
  MAT_DENOMINATOR_CLASS_UNDISCLOSED: 'MAT_DENOMINATOR_CLASS_UNDISCLOSED',
  MAT_SUBJECTIVE_JOIN_REFUSED: 'MAT_SUBJECTIVE_JOIN_REFUSED',
  MAT_PROMOTION_EVIDENCE_INSUFFICIENT: 'MAT_PROMOTION_EVIDENCE_INSUFFICIENT',
  MAT_CAPACITY_DISCLOSURE_MISSING: 'MAT_CAPACITY_DISCLOSURE_MISSING',
  // --- outcome evaluation and statistical integrity (FR-EVAL-001…009)
  EVAL_PARTITION_UNKNOWN: 'EVAL_PARTITION_UNKNOWN',
  EVAL_HOLDOUT_EXPOSURE_UNKNOWN: 'EVAL_HOLDOUT_EXPOSURE_UNKNOWN',
  EVAL_REPLAY_KIND_UNKNOWN: 'EVAL_REPLAY_KIND_UNKNOWN',
  EVAL_TESTING_FAMILY_UNKNOWN: 'EVAL_TESTING_FAMILY_UNKNOWN',
  EVAL_CONTROL_KIND_UNKNOWN: 'EVAL_CONTROL_KIND_UNKNOWN',
  EVAL_INCIDENT_TRIGGER_UNKNOWN: 'EVAL_INCIDENT_TRIGGER_UNKNOWN',
  EVAL_BASELINE_KIND_UNKNOWN: 'EVAL_BASELINE_KIND_UNKNOWN',
  EVAL_INTERVAL_METHOD_UNKNOWN: 'EVAL_INTERVAL_METHOD_UNKNOWN',
  EVAL_CLUSTER_DEFINITION_UNKNOWN: 'EVAL_CLUSTER_DEFINITION_UNKNOWN',
  EVAL_DRIFT_KIND_UNKNOWN: 'EVAL_DRIFT_KIND_UNKNOWN',
  EVAL_CLAIM_RESTRICTION_UNKNOWN: 'EVAL_CLAIM_RESTRICTION_UNKNOWN',
  EVAL_HOLDOUT_EXHAUSTED_REUSED: 'EVAL_HOLDOUT_EXHAUSTED_REUSED',
  EVAL_UNIVERSE_MISMATCH: 'EVAL_UNIVERSE_MISMATCH',
  EVAL_POPULATION_CLAIM_UNSUPPORTED: 'EVAL_POPULATION_CLAIM_UNSUPPORTED',
  EVAL_WEIGHTING_INVALID: 'EVAL_WEIGHTING_INVALID',
  EVAL_ACTION_TIME_ASYMMETRY: 'EVAL_ACTION_TIME_ASYMMETRY',
  EVAL_NETWORK_ACCESS_DENIED: 'EVAL_NETWORK_ACCESS_DENIED',
  EVAL_ESS_BELOW_GATE: 'EVAL_ESS_BELOW_GATE',
  // --- durable workflow (§25)
  WF_TRIGGER_STATUS_UNKNOWN: 'WF_TRIGGER_STATUS_UNKNOWN',
  WF_RUN_STATUS_UNKNOWN: 'WF_RUN_STATUS_UNKNOWN',
  WF_STEP_STATUS_UNKNOWN: 'WF_STEP_STATUS_UNKNOWN',
  WF_SCHEDULE_STATUS_UNKNOWN: 'WF_SCHEDULE_STATUS_UNKNOWN',
  WF_CONCURRENCY_POLICY_UNKNOWN: 'WF_CONCURRENCY_POLICY_UNKNOWN',
  WF_RETRY_ERROR_CLASS_UNKNOWN: 'WF_RETRY_ERROR_CLASS_UNKNOWN',
  WF_OUTBOX_STATUS_UNKNOWN: 'WF_OUTBOX_STATUS_UNKNOWN',
  WF_DEAD_LETTER_STATUS_UNKNOWN: 'WF_DEAD_LETTER_STATUS_UNKNOWN',
  WF_SCHEDULE_ACTION_UNKNOWN: 'WF_SCHEDULE_ACTION_UNKNOWN',
  // scheduler delivery trust boundary (ADR-G2WF-2, §9.3/§25.3)
  WF_SCHEDULER_SIGNATURE_INVALID: 'WF_SCHEDULER_SIGNATURE_INVALID',
  WF_SCHEDULER_TIMESTAMP_OUT_OF_WINDOW: 'WF_SCHEDULER_TIMESTAMP_OUT_OF_WINDOW',
  WF_SCHEDULER_TIMESTAMP_INVALID: 'WF_SCHEDULER_TIMESTAMP_INVALID',
  WF_SCHEDULER_DELIVERY_REPLAYED: 'WF_SCHEDULER_DELIVERY_REPLAYED',
  WF_SCHEDULER_NOT_FOUND: 'WF_SCHEDULER_NOT_FOUND',
  WF_SCHEDULER_TRANSPORT_FAILED: 'WF_SCHEDULER_TRANSPORT_FAILED',
  // trigger inbox (§25.2/§25.3)
  WF_TRIGGER_IDENTITY_INVALID: 'WF_TRIGGER_IDENTITY_INVALID',
  WF_TRIGGER_DELIVERY_REJECTED: 'WF_TRIGGER_DELIVERY_REJECTED',
  WF_TRIGGER_PAYLOAD_HASH_INVALID: 'WF_TRIGGER_PAYLOAD_HASH_INVALID',
  // A delivery reused another schedule's external message identity (§25.3).
  WF_TRIGGER_SCHEDULE_MISMATCH: 'WF_TRIGGER_SCHEDULE_MISMATCH',
  // schedules and immutable versions (§25.11)
  WF_SCHEDULE_NOT_FOUND: 'WF_SCHEDULE_NOT_FOUND',
  WF_SCHEDULE_NOT_ACTIVE: 'WF_SCHEDULE_NOT_ACTIVE',
  WF_SCHEDULE_PAUSED: 'WF_SCHEDULE_PAUSED',
  WF_SCHEDULE_DISABLED: 'WF_SCHEDULE_DISABLED',
  WF_SCHEDULE_VERSION_NOT_FOUND: 'WF_SCHEDULE_VERSION_NOT_FOUND',
  WF_SCHEDULE_VERSION_IMMUTABLE: 'WF_SCHEDULE_VERSION_IMMUTABLE',
  WF_SCHEDULE_TRANSITION_INVALID: 'WF_SCHEDULE_TRANSITION_INVALID',
  WF_SCHEDULE_CONFIG_INVALID: 'WF_SCHEDULE_CONFIG_INVALID',
  WF_SCHEDULE_CRON_INVALID: 'WF_SCHEDULE_CRON_INVALID',
  WF_SCHEDULE_TIMEZONE_INVALID: 'WF_SCHEDULE_TIMEZONE_INVALID',
  // §33.6 forecast-before-enable gate (AC-063)
  WF_FORECAST_MISSING: 'WF_FORECAST_MISSING',
  WF_FORECAST_STALE: 'WF_FORECAST_STALE',
  // steps (§25.4/§25.5)
  WF_STEP_NOT_FOUND: 'WF_STEP_NOT_FOUND',
  WF_STEP_ORDER_INVALID: 'WF_STEP_ORDER_INVALID',
  WF_STEP_INPUT_HASH_MISMATCH: 'WF_STEP_INPUT_HASH_MISMATCH',
  WF_STEP_TRANSITION_INVALID: 'WF_STEP_TRANSITION_INVALID',
  // retries (§25.8)
  WF_RETRY_POLICY_INVALID: 'WF_RETRY_POLICY_INVALID',
  // runs (exhaustion handoff, §25.9)
  WF_RUN_NOT_FOUND: 'WF_RUN_NOT_FOUND',
  // notification channels (§26.6/§26.9)
  WF_NOTIFICATION_CHANNEL_FAILED: 'WF_NOTIFICATION_CHANNEL_FAILED',
  WF_NOTIFICATION_CHANNEL_CRASHED: 'WF_NOTIFICATION_CHANNEL_CRASHED',
  // transactional outbox commit + delivery (§26.5, AC-011)
  WF_OUTBOX_PAYLOAD_INVALID: 'WF_OUTBOX_PAYLOAD_INVALID',
  WF_OUTBOX_NOT_FOUND: 'WF_OUTBOX_NOT_FOUND',
  WF_OUTBOX_CLAIM_STALE: 'WF_OUTBOX_CLAIM_STALE',
  WF_OUTBOX_TRANSITION_INVALID: 'WF_OUTBOX_TRANSITION_INVALID',
  WF_OUTBOX_SUPPRESSED: 'WF_OUTBOX_SUPPRESSED',
  // shadow mode (FR-WF-008)
  WF_SHADOW_INFLUENCE_REFUSED: 'WF_SHADOW_INFLUENCE_REFUSED',
  // dead-letter management (§25.9, FR-WF-007)
  WF_DEAD_LETTER_NOT_FOUND: 'WF_DEAD_LETTER_NOT_FOUND',
  WF_DEAD_LETTER_NO_CHECKPOINT: 'WF_DEAD_LETTER_NO_CHECKPOINT',
  WF_DEAD_LETTER_TRANSITION_INVALID: 'WF_DEAD_LETTER_TRANSITION_INVALID',
  // reconciliation + state verification (§25.10, recovery seam)
  WF_RECONCILIATION_CHECK_INVALID: 'WF_RECONCILIATION_CHECK_INVALID',
  WF_RECONCILIATION_REPAIR_REFUSED: 'WF_RECONCILIATION_REPAIR_REFUSED',
  WF_STATE_CHECK_UNKNOWN: 'WF_STATE_CHECK_UNKNOWN',
  // --- alerts (§26, FR-ALERT-001…005)
  ALERT_CLASS_UNKNOWN: 'ALERT_CLASS_UNKNOWN',
  ALERT_UPDATE_KIND_UNKNOWN: 'ALERT_UPDATE_KIND_UNKNOWN',
  ALERT_STATE_UNKNOWN: 'ALERT_STATE_UNKNOWN',
  ALERT_ACTIONABILITY_UNKNOWN: 'ALERT_ACTIONABILITY_UNKNOWN',
  ALERT_CANCELLATION_STATE_UNKNOWN: 'ALERT_CANCELLATION_STATE_UNKNOWN',
  ALERT_LIFECYCLE_STATE_UNKNOWN: 'ALERT_LIFECYCLE_STATE_UNKNOWN',
  ALERT_RISK_STATE_UNKNOWN: 'ALERT_RISK_STATE_UNKNOWN',
  ALERT_SOCIAL_CAPABILITY_UNKNOWN: 'ALERT_SOCIAL_CAPABILITY_UNKNOWN',
  ALERT_DECISION_KIND_UNKNOWN: 'ALERT_DECISION_KIND_UNKNOWN',
  ALERT_MULTIVIEW_STATE_UNKNOWN: 'ALERT_MULTIVIEW_STATE_UNKNOWN',
  ALERT_NOVELTY_STATE_UNKNOWN: 'ALERT_NOVELTY_STATE_UNKNOWN',
  ALERT_COST_POLICY_RESULT_UNKNOWN: 'ALERT_COST_POLICY_RESULT_UNKNOWN',
  ALERT_METRIC_KEY_UNKNOWN: 'ALERT_METRIC_KEY_UNKNOWN',
  // A metric observation whose key does not belong to its alert class (FR-ALERT-005).
  ALERT_METRIC_CLASS_MISMATCH: 'ALERT_METRIC_CLASS_MISMATCH',
  ALERT_GATE_UNKNOWN: 'ALERT_GATE_UNKNOWN',
  // The §26.3 confirmed-opportunity gate set was not evaluated exactly once per gate.
  ALERT_GATE_SET_INCOMPLETE: 'ALERT_GATE_SET_INCOMPLETE',
  ALERT_SUPPRESSION_REASON_UNKNOWN: 'ALERT_SUPPRESSION_REASON_UNKNOWN',
  ALERT_FINGERPRINT_OUTCOME_UNKNOWN: 'ALERT_FINGERPRINT_OUTCOME_UNKNOWN',
  ALERT_LATENCY_OUTCOME_UNKNOWN: 'ALERT_LATENCY_OUTCOME_UNKNOWN',
  ALERT_FINGERPRINT_INPUT_INVALID: 'ALERT_FINGERPRINT_INPUT_INVALID',
  ALERT_MATERIAL_STATE_INVALID: 'ALERT_MATERIAL_STATE_INVALID',
  // FR-ALERT-002: an EARLY_WATCH (or other non-conviction class) body used buy/high-conviction language.
  ALERT_HIGH_CONVICTION_LANGUAGE: 'ALERT_HIGH_CONVICTION_LANGUAGE',
  // A class resolved to no policy row (defensive; the six-class registry is total).
  ALERT_POLICY_UNKNOWN: 'ALERT_POLICY_UNKNOWN',
  // --- production readiness (§32)
  PROD_MODULE_STATE_UNKNOWN: 'PROD_MODULE_STATE_UNKNOWN',
  PROD_OPERATIONAL_READINESS_UNKNOWN: 'PROD_OPERATIONAL_READINESS_UNKNOWN',
  PROD_DISTRIBUTION_READINESS_UNKNOWN: 'PROD_DISTRIBUTION_READINESS_UNKNOWN',
  PROD_DEPLOYMENT_POSTURE_UNKNOWN: 'PROD_DEPLOYMENT_POSTURE_UNKNOWN',
  PROD_ACTIVATION_GATE_KIND_UNKNOWN: 'PROD_ACTIVATION_GATE_KIND_UNKNOWN',
  PROD_ACTIVATION_VERDICT_UNKNOWN: 'PROD_ACTIVATION_VERDICT_UNKNOWN',
  PROD_CHANGE_CLASSIFICATION_UNKNOWN: 'PROD_CHANGE_CLASSIFICATION_UNKNOWN',
  PROD_CONTAINMENT_ACTION_UNKNOWN: 'PROD_CONTAINMENT_ACTION_UNKNOWN',
  PROD_MCP_REVISION_CHANNEL_UNKNOWN: 'PROD_MCP_REVISION_CHANNEL_UNKNOWN',
  PROD_MCP_CONFORMANCE_RESULT_UNKNOWN: 'PROD_MCP_CONFORMANCE_RESULT_UNKNOWN',
  PROD_PROTECTED_DIMENSION_UNKNOWN: 'PROD_PROTECTED_DIMENSION_UNKNOWN',
  PROD_RELAXABLE_DIMENSION_UNKNOWN: 'PROD_RELAXABLE_DIMENSION_UNKNOWN',
  PROD_ARTIFACT_BOUNDARY_KIND_UNKNOWN: 'PROD_ARTIFACT_BOUNDARY_KIND_UNKNOWN',
  PROD_DEPENDENCY_GROUP_UNKNOWN: 'PROD_DEPENDENCY_GROUP_UNKNOWN',
  // §69.2/§69.3: the requested lifecycle transition is not a legal governed-state edge.
  PROD_LIFECYCLE_TRANSITION_ILLEGAL: 'PROD_LIFECYCLE_TRANSITION_ILLEGAL',
  // §69.5: the activation scope is malformed or its gate schedule contradicts it.
  PROD_ACTIVATION_SCOPE_INVALID: 'PROD_ACTIVATION_SCOPE_INVALID',
  // §69.4/§69.5: the ordered activation gate set is incomplete or refused.
  PROD_ACTIVATION_GATE_REFUSED: 'PROD_ACTIVATION_GATE_REFUSED',
  // §40: dependency groups are build/test ordering and never activate opportunities.
  PROD_DEPENDENCY_ORDER_VIOLATED: 'PROD_DEPENDENCY_ORDER_VIOLATED',
  // §69.6/AC-153: a best-effort declaration weakened a protected dimension.
  PROD_BEST_EFFORT_PROTECTED_DIMENSION: 'PROD_BEST_EFFORT_PROTECTED_DIMENSION',
  // §69.7/AC-144: a draft revision was marked the compatibility default.
  PROD_MCP_DRAFT_DEFAULT: 'PROD_MCP_DRAFT_DEFAULT',
  // §33.7/AC-279: a precomputed bound is unbounded, expired, or exceeded.
  PROD_PRECOMPUTED_BOUND_INVALID: 'PROD_PRECOMPUTED_BOUND_INVALID',
  // §10.3/§35.14: a live path reached a heavy job, import, or provider call.
  PROD_TRUST_BOUNDARY_VIOLATION: 'PROD_TRUST_BOUNDARY_VIOLATION',
  // --- generic contract violations
  CONTRACT_INVARIANT_VIOLATED: 'CONTRACT_INVARIANT_VIOLATED',
} as const;

/** Closed discovery vocabularies shared by schemas, persistence, and telemetry. */
export const DiscEntryReason = {
  FIRST_PARTY_SUPPORTED_PROGRAM_EVENT: 'FIRST_PARTY_SUPPORTED_PROGRAM_EVENT',
  FREE_AGGREGATE_OBSERVATION: 'FREE_AGGREGATE_OBSERVATION',
  AUTHORIZED_LAUNCH_NOTIFICATION: 'AUTHORIZED_LAUNCH_NOTIFICATION',
  USER_WATCHLIST_ADDITION: 'USER_WATCHLIST_ADDITION',
  AUTHORIZED_SOCIAL_MENTION: 'AUTHORIZED_SOCIAL_MENTION',
  SELECTIVE_VERIFICATION_HIT: 'SELECTIVE_VERIFICATION_HIT',
  RETROSPECTIVE_ENUMERATION_HIT: 'RETROSPECTIVE_ENUMERATION_HIT',
  STRATIFIED_SAMPLE_DRAW: 'STRATIFIED_SAMPLE_DRAW',
} as const;
export const ALL_DISC_ENTRY_REASONS = Object.values(DiscEntryReason);

export const DiscRightsBasis = {
  FIRST_PARTY_COLLECTOR: 'FIRST_PARTY_COLLECTOR',
  AUTHORIZED_FEED_CONTRACT: 'AUTHORIZED_FEED_CONTRACT',
  FREE_PUBLIC_TERMS: 'FREE_PUBLIC_TERMS',
  USER_PROVIDED: 'USER_PROVIDED',
  EXCLUDED: 'EXCLUDED',
} as const;
export const ALL_DISC_RIGHTS_BASES = Object.values(DiscRightsBasis);

export const DiscManipulationPolicy = {
  LABEL_AND_RETAIN: 'LABEL_AND_RETAIN',
  LABEL_AND_DOWNWEIGHT: 'LABEL_AND_DOWNWEIGHT',
  EXCLUDE_PAID_PLACEMENTS: 'EXCLUDE_PAID_PLACEMENTS',
} as const;
export const ALL_DISC_MANIPULATION_POLICIES = Object.values(DiscManipulationPolicy);

export const DiscClaimBasis = {
  INDEPENDENT_FIRST_PARTY_OBSERVATION: 'INDEPENDENT_FIRST_PARTY_OBSERVATION',
  INDEPENDENT_PROVIDER_LINEAGE: 'INDEPENDENT_PROVIDER_LINEAGE',
  KNOWN_INCLUSION_PROBABILITIES: 'KNOWN_INCLUSION_PROBABILITIES',
} as const;
export const ALL_DISC_CLAIM_BASES = Object.values(DiscClaimBasis);

export const DiscConstraintKind = {
  COLLECTOR_GAP: 'COLLECTOR_GAP',
  DECODER_OUTAGE: 'DECODER_OUTAGE',
  UNVERIFIED_PROGRAM_VERSION: 'UNVERIFIED_PROGRAM_VERSION',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  RIGHTS_EXCLUSION: 'RIGHTS_EXCLUSION',
  IDENTITY_UNRESOLVED: 'IDENTITY_UNRESOLVED',
} as const;
export const ALL_DISC_CONSTRAINT_KINDS = Object.values(DiscConstraintKind);

export const DiscConstraintEffect = {
  NARROW_CLAIM: 'NARROW_CLAIM',
  EXCLUDE_WINDOW: 'EXCLUDE_WINDOW',
  BLOCK_CLAIM: 'BLOCK_CLAIM',
} as const;
export const ALL_DISC_CONSTRAINT_EFFECTS = Object.values(DiscConstraintEffect);

export const DiscChainAccessPurpose = {
  VERIFICATION: 'VERIFICATION',
  RETROSPECTIVE_BACKFILL: 'RETROSPECTIVE_BACKFILL',
} as const;
export const ALL_DISC_CHAIN_ACCESS_PURPOSES = Object.values(DiscChainAccessPurpose);

export const DiscRecallVerdict = {
  INDEPENDENT_ESTIMATE: 'INDEPENDENT_ESTIMATE',
  DEPENDENT_DISCLOSED: 'DEPENDENT_DISCLOSED',
  SELF_RECALL_REFUSED: 'SELF_RECALL_REFUSED',
  NO_ADMISSIBLE_BASIS: 'NO_ADMISSIBLE_BASIS',
} as const;
export const ALL_DISC_RECALL_VERDICTS = Object.values(DiscRecallVerdict);

export const DiscLatenessBasis = {
  SOURCE_OBSERVED_AT: 'SOURCE_OBSERVED_AT',
  SOURCE_PUBLISHED_AT: 'SOURCE_PUBLISHED_AT',
  SOURCE_AVAILABLE_AT: 'SOURCE_AVAILABLE_AT',
} as const;
export const ALL_DISC_LATENESS_BASES = Object.values(DiscLatenessBasis);

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Context carried alongside a machine code (never secrets). */
export type ErrorDetail = Readonly<Record<string, string | number | boolean | null>>;

/** Base class for every refusal this system raises. Fail-closed by construction. */
export class ForesiftError extends Error {
  readonly code: ErrorCode;
  readonly detail: ErrorDetail;

  constructor(code: ErrorCode, message: string, detail: ErrorDetail = {}) {
    super(`${code}: ${message}`);
    this.name = 'ForesiftError';
    this.code = code;
    this.detail = detail;
  }
}

function subclass(
  name: string,
  defaultCode: ErrorCode,
): new (message: string, detail?: ErrorDetail, code?: ErrorCode) => ForesiftError {
  return class extends ForesiftError {
    constructor(message: string, detail: ErrorDetail = {}, code: ErrorCode = defaultCode) {
      super(code, message, detail);
      this.name = name;
    }
  };
}

/** FR-DATA-001 identity refusals. */
export class IdentityError extends subclass(
  'IdentityError',
  ErrorCode.CONTRACT_INVARIANT_VIOLATED,
) {}
/** §11.5 numeric-policy refusals. */
export class QuantityError extends subclass(
  'QuantityError',
  ErrorCode.QUANTITY_DECIMAL_STRING_INVALID,
) {}
/** FR-DATA-002 observation/revision immutability refusals. */
export class ObservationError extends subclass(
  'ObservationError',
  ErrorCode.OBSERVATION_IMMUTABLE,
) {}
/** FR-DATA-003 replay/temporal refusals. */
export class ReplayError extends subclass('ReplayError', ErrorCode.REPLAY_BOUNDARY_VIOLATION) {}
/** FR-DATA-005 quality-code refusals ("null alone is insufficient"). */
export class QualityError extends subclass('QualityError', ErrorCode.QUALITY_CODE_UNKNOWN) {}
/** §13.8 acquisition-contract refusals. */
export class AcquisitionError extends subclass(
  'AcquisitionError',
  ErrorCode.ACQUISITION_STATE_UNKNOWN,
) {}
/** FR-DATA-004 feature-consistency refusals. */
export class FeatureError extends subclass(
  'FeatureError',
  ErrorCode.FEATURE_PROVENANCE_INCOMPLETE,
) {}
/** FR-DATA-006 source-lineage refusals. */
export class SourceError extends subclass(
  'SourceError',
  ErrorCode.SOURCE_DEPENDENCE_INPUT_INVALID,
) {}
/** INV-009 checkpoint/fencing refusals. */
export class CheckpointError extends subclass(
  'CheckpointError',
  ErrorCode.CHECKPOINT_STALE_FENCING_TOKEN,
) {}
/** Object-store / staged-commit refusals. */
export class ObjectStoreError extends subclass(
  'ObjectStoreError',
  ErrorCode.OBJECT_HASH_MISMATCH,
) {}
/** Recovery/backup/restore refusals. */
export class RecoveryError extends subclass(
  'RecoveryError',
  ErrorCode.RESTORE_VERIFICATION_FAILED,
) {}
/** FR-DISC-006…014 discovery coverage, provenance, and claim refusals. */
export class DiscError extends subclass('DiscError', ErrorCode.DISC_CLAIM_BASIS_UNKNOWN) {}
/** FR-MAT-001…012 maturity, denominator, and promotion-evidence refusals. */
export class MatError extends subclass('MatError', ErrorCode.MAT_TRANSITION_ILLEGAL) {}
/** FR-EVAL-001…009 evaluation and statistical-integrity refusals. */
export class EvalError extends subclass('EvalError', ErrorCode.EVAL_PARTITION_UNKNOWN) {}

/** Narrowing guard for Foresift errors. */
export function isForesiftError(value: unknown): value is ForesiftError {
  return value instanceof ForesiftError;
}
