// PLANNED-HANDOFF ACCEPTANCE (post-planning throughput gap).
//
// Law under test: an unplanned wave-eligible package takes the planning-ONLY
// bootstrap (zero implementation nodes); when its planning truth becomes
// deterministically complete that execution TERMINATES, and the supervisor
// performs a first-class handoff — verify at the run worktree, promote the
// scoped planning artifacts to main, and IMMEDIATELY reselect the SAME
// still-RUNNING package into `foresift-sharded-wave`. Crash-safe,
// duplicate-safe, adoption-safe, generation-aware; legacy topologies
// untouched.
//
// Layers:
//   1. Structural — the bootstrap DAG cannot dispatch an implementation
//      provider because no such node exists.
//   2. CLI flows — the REAL supervisor subprocess against hermetic git
//      fixtures + a scripted archon stub, covering launch demotion (A),
//      direct wave admission (E), the completed-bootstrap handoff
//      (B/C/D/G/H/I), legacy preservation (F), and artifact preservation
//      (J).
import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { disposeGitFixtureBase, gitFixture, type GitFixture } from '../helpers/git-fixture.js';

const AUTOPILOT = fileURLToPath(
  new URL('../../scripts/automation/foresift-autopilot.mjs', import.meta.url),
);
const BOOTSTRAP_YAML = fileURLToPath(
  new URL(
    '../../.archon/workflows/foresift/foresift-package-planning-bootstrap.yaml',
    import.meta.url,
  ),
);
const WAVE_YAML = fileURLToPath(
  new URL('../../.archon/workflows/foresift/foresift-sharded-wave.yaml', import.meta.url),
);
const PKG = 'pkg-alpha';
const BOOTSTRAP_WF = 'foresift-package-planning-bootstrap';
const WAVE_WF = 'foresift-sharded-wave';
const OPTIMIZED_WF = 'foresift-work-package-optimized';

// ── structural: the planning bootstrap cannot implement ─────────────────────
describe('structural: planning-bootstrap DAG carries zero implementation nodes', () => {
  const yaml = readFileSync(BOOTSTRAP_YAML, 'utf8');
  const waveYaml = readFileSync(WAVE_YAML, 'utf8');

  it('has no implementation/gate/landing provider commands (B: zero impl calls by construction)', () => {
    for (const forbidden of [
      'foresift-wp-implement',
      'foresift-wp-gate',
      'package-full-gate',
      'package-create-pr',
      'package-final-land',
    ]) {
      expect(yaml).not.toContain(forbidden);
    }
  });

  it('is the optimized Phases 0A–1 verbatim plus ONE terminal handoff node', () => {
    for (const required of [
      'adopt-generation-branch.mjs',
      'preflight.mjs',
      'package-plan-complete.mjs',
      'command: foresift-wp-plan',
      'none_failed_min_one_success',
      'PLANNING_BOOTSTRAP_COMPLETE',
    ]) {
      expect(yaml).toContain(required);
    }
    // The terminal handoff node is the LAST node and nothing depends on a
    // phase-2 router: no impl-status anywhere.
    expect(yaml).not.toContain('impl-status');
  });

  it('the wave DAG pins its integration base only AFTER branch adoption', () => {
    const adoptionIdx = waveYaml.indexOf('- id: branch-adoption');
    const prepIdx = waveYaml.indexOf('- id: prep');
    const basePinIdx = waveYaml.indexOf('BASE="$(git rev-parse HEAD)"');
    expect(adoptionIdx).toBeGreaterThan(-1);
    expect(prepIdx).toBeGreaterThan(adoptionIdx);
    expect(basePinIdx).toBeGreaterThan(prepIdx);
    expect(waveYaml).toContain('wave-branch-adoption.mjs');
  });
});

// ── hermetic supervisor sandbox ──────────────────────────────────────────────
let scratch: string;
beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'planned-handoff-'));
});
afterAll(() => {
  disposeGitFixtureBase();
});

const SPEC = [
  `# ${PKG} scoped specification`,
  '',
  'Subordinate to the PRD; binds FR-A-001 and FR-A-002 with acceptance',
  'criteria and test references. No unresolved markers.',
  '',
].join('\n');
const PLAN = [
  `# ${PKG} implementation plan`,
  '',
  'Architecture, approach, and trade-offs for FR-A-001 / FR-A-002 delivery.',
  'Generated by the scoped planner; complete and traceable.',
  '',
].join('\n');
const TASKS = [
  '- [x] T101 Groundwork for `packages/a/src/base.ts`. Traces: FR-A-001.',
  '- [ ] T102 Implement alpha in `packages/a/src/alpha.ts`. Traces: FR-A-001, FR-A-002.',
  '',
].join('\n');

function milestoneFixture(status: string) {
  return {
    schemaVersion: '1.0.0',
    milestoneId: 'G0',
    status: 'ACTIVE',
    packages: [
      {
        id: PKG,
        objective: 'Implement subsystem alpha end to end with full evidence coverage.',
        requirementIds: ['FR-A-001', 'FR-A-002'],
        dependencies: [],
        risk: 'HIGH',
        parallelizable: false,
        writeScopes: ['packages/**'],
        verificationCommands: ['pnpm test'],
        status,
      },
      {
        // Milestones decompose into 2-8 packages (schema law); beta is a
        // dependent sibling so alpha stays the only selectable candidate.
        id: 'pkg-beta',
        objective: 'Implement subsystem beta after alpha lands, with evidence coverage.',
        requirementIds: ['FR-A-003'],
        dependencies: [PKG],
        risk: 'MEDIUM',
        parallelizable: false,
        writeScopes: ['packages/**'],
        verificationCommands: ['pnpm test'],
        status: 'PENDING',
      },
    ],
  };
}

const ROADMAP = {
  schemaVersion: '1.0.0',
  policy: {
    foundationMilestones: ['G0'],
    maxParallelCodingPackagesFoundation: 1,
    maxParallelCodingPackages: 2,
  },
  currentMilestoneId: 'G0',
  milestones: [{ id: 'G0', name: 'foundation', dependsOn: [], status: 'ACTIVE' }],
};

interface Sandbox {
  fx: GitFixture;
  stateDir: string;
  /** A stand-in "run worktree" carrying complete scoped planning artifacts. */
  wtDir: string;
}

function writePlannedTree(dir: string) {
  mkdirSync(join(dir, 'specs', PKG), { recursive: true });
  mkdirSync(join(dir, 'specs', 'implementation'), { recursive: true });
  writeFileSync(join(dir, 'specs', PKG, 'spec.md'), SPEC);
  writeFileSync(join(dir, 'specs', PKG, 'plan.md'), PLAN);
  writeFileSync(join(dir, 'specs', PKG, 'tasks.md'), TASKS);
  writeFileSync(
    join(dir, 'specs', 'implementation', 'current-milestone.json'),
    JSON.stringify(milestoneFixture('RUNNING'), null, 2) + '\n',
  );
}

function makeSandbox(
  name: string,
  pkgStatus: string,
  opts: { plannedOnMain?: boolean } = {},
): Sandbox {
  const fx = gitFixture(name);
  // Unplanned sandboxes carry NO specs/<pkg>/ anywhere; planned ones carry the
  // full scoped planning truth on main. The launch-status milestone is written
  // LAST so the planned tree cannot flip the tracked package to RUNNING
  // without a supervisor-tracked run (stranded reconciliation would pause).
  if (opts.plannedOnMain) writePlannedTree(fx.root);
  fx.writeFile(
    'specs/implementation/current-milestone.json',
    JSON.stringify(milestoneFixture(pkgStatus), null, 2),
  );
  fx.writeFile('specs/implementation/roadmap.json', JSON.stringify(ROADMAP, null, 2));
  fx.commitAll('fixture state');
  fx.g(['push', '-q', 'origin', 'main']);

  const stateDir = mkdtempSync(join(scratch, `${name}-state-`));
  const wtDir = join(scratch, `${name}-wt`);
  writePlannedTree(wtDir);
  return { fx, stateDir, wtDir };
}

function writeJson(path: string, v: unknown) {
  writeFileSync(path, JSON.stringify(v));
}

/** Archon stub: logs every invocation; per-run `get` statuses; scripted runs table. */
function stubDir() {
  return join(scratch, 'stub-bin');
}
function installStub() {
  const dir = stubDir();
  mkdirSync(dir, { recursive: true });
  const p = join(dir, 'archon');
  writeFileSync(
    p,
    [
      '#!/usr/bin/env bash',
      'printf \'%s\\n\' "$*" >> "${FAKE_ARCHON_LOG:?}"',
      'case "$1 $2" in',
      '  "workflow runs") cat "${FAKE_RUNS_FILE:?}" ;;',
      '  "workflow abandon") printf \'{"ok":true}\\n\' ;;',
      '  "workflow get") node -e "const fs=require(\'fs\');const m=JSON.parse(fs.readFileSync(process.env.FAKE_GET_FILE,\'utf8\'));console.log(JSON.stringify(m[process.argv[1]]??{id:process.argv[1],status:\'running\',last_activity_at:Date.now(),started_at:Date.now()}))" "$3" ;;',
      '  *) printf \'{"ok":true,"action":"run","detached":true}\\n\' ;;',
      'esac',
    ].join('\n'),
  );
  chmodSync(p, 0o755);
}

interface TickOpts {
  rows?: unknown[];
  getMap?: Record<string, unknown>;
  env?: Record<string, string>;
}

function tick(sandbox: Sandbox, args: string[] = ['--once'], opts: TickOpts = {}) {
  writeJson(join(sandbox.stateDir, 'fake-runs.json'), { runs: opts.rows ?? [] });
  writeJson(join(sandbox.stateDir, 'fake-get.json'), opts.getMap ?? {});
  return spawnSync('node', [AUTOPILOT, ...args], {
    cwd: sandbox.fx.root,
    encoding: 'utf8',
    env: {
      ...process.env,
      FORESIFT_AUTOPILOT_REPO: sandbox.fx.root,
      FORESIFT_AUTOPILOT_STATE_DIR: sandbox.stateDir,
      FORESIFT_SALVAGE_SKIP_INSTALL: '1',
      PATH: `${stubDir()}:${process.env.PATH ?? ''}`,
      FAKE_ARCHON_LOG: join(sandbox.stateDir, 'archon.log'),
      FAKE_RUNS_FILE: join(sandbox.stateDir, 'fake-runs.json'),
      FAKE_GET_FILE: join(sandbox.stateDir, 'fake-get.json'),
      GIT_AUTHOR_NAME: 't',
      GIT_COMMITTER_NAME: 't',
      GIT_AUTHOR_EMAIL: 't@t',
      GIT_COMMITTER_EMAIL: 't@t',
      GIT_CONFIG_GLOBAL: '/dev/null',
      GIT_CONFIG_SYSTEM: '/dev/null',
      ...opts.env,
    },
  });
}

const readState = (sandbox: Sandbox) =>
  JSON.parse(readFileSync(join(sandbox.stateDir, 'autopilot-state.json'), 'utf8'));
const archonLog = (sandbox: Sandbox) => readFileSync(join(sandbox.stateDir, 'archon.log'), 'utf8');
const readMs = (sandbox: Sandbox) =>
  JSON.parse(
    readFileSync(
      join(sandbox.fx.root, 'specs', 'implementation', 'current-milestone.json'),
      'utf8',
    ),
  );

function bootstrapEntry(overrides: Record<string, unknown> = {}) {
  return {
    kind: 'package',
    workflow: BOOTSTRAP_WF,
    runId: 'boot-1',
    packageId: PKG,
    branch: `foresift/${PKG}`,
    message: PKG,
    startedAt: Date.now() - 60_000,
    resumeCount: 0,
    restartCount: 0,
    awaitingDiscovery: false,
    discoveryAttempts: 0,
    lastSeenStatus: 'running',
    lastSeenAt: Date.now(),
    ...overrides,
  };
}

function seedState(sandbox: Sandbox, activeRuns: unknown[]) {
  writeJson(join(sandbox.stateDir, 'autopilot-state.json'), {
    activeRuns,
    milestoneRuns: [],
    pausedFatal: null,
    history: [],
  });
}

// ── A / E: launch-seam selection ─────────────────────────────────────────────
describe('launch seam (A: unplanned → planner-capable path · E: planned → direct wave)', () => {
  it('A: an unplanned wave-eligible package launches the planning-only bootstrap, never the wave prep', () => {
    const sb = makeSandbox('unplanned-launch', 'PENDING');
    installStub();
    const r = tick(sb);
    expect(r.status).toBe(0);
    const st = readState(sb);
    expect(st.history.map((h: { event: string }) => h.event)).toContain('work_package_launched');
    expect(st.activeRuns[0]?.workflow).toBe(BOOTSTRAP_WF);
    const log = archonLog(sb);
    expect(log).toContain(`run ${BOOTSTRAP_WF}`);
    expect(log).not.toContain(`run ${WAVE_WF}`);
    expect(log).not.toContain(`run ${OPTIMIZED_WF}`);
  });

  it('E: a planned package at initial launch goes straight to the sharded wave', () => {
    const sb = makeSandbox('planned-launch', 'PENDING', { plannedOnMain: true });
    installStub();
    const r = tick(sb);
    expect(r.status).toBe(0);
    const st = readState(sb);
    expect(st.activeRuns[0]?.workflow).toBe(WAVE_WF);
    const log = archonLog(sb);
    expect(log).toContain(`run ${WAVE_WF}`);
    expect(log).not.toContain(`run ${BOOTSTRAP_WF}`);
  });
});

// ── B/C/D: the completed-bootstrap handoff ───────────────────────────────────
describe('planning handoff (B: zero impl calls · C: RUNNING preserved · D: immediate wave reselect)', () => {
  function handoffSandbox(name: string) {
    const sb = makeSandbox(name, 'RUNNING');
    installStub();
    seedState(sb, [bootstrapEntry()]);
    return sb;
  }

  it('completing the bootstrap promotes ONLY scoped planning artifacts and relaunches the SAME package into the wave in the SAME tick', () => {
    const sb = handoffSandbox('handoff-happy');
    const r = tick(sb, ['--once'], {
      getMap: { 'boot-1': { id: 'boot-1', status: 'completed', working_path: sb.wtDir } },
    });
    expect(r.status).toBe(0);

    const st = readState(sb);
    const events = st.history.map((h: { event: string }) => h.event);
    expect(events).toContain('planning_handoff_complete');

    // C: package status NEVER left RUNNING (no PENDING-forcing, no PROVEN fabrication).
    expect(readMs(sb).packages.find((p: { id: string }) => p.id === PKG)?.status).toBe('RUNNING');

    // D: immediate reselection — the wave launch happened in this very tick.
    const log = archonLog(sb);
    const waveLaunches = log.split('\n').filter((l) => l.includes(`run ${WAVE_WF} --detach`));
    expect(waveLaunches).toHaveLength(1);
    expect(log).not.toContain(`run ${BOOTSTRAP_WF} --detach`);

    // The old bootstrap execution is terminal/non-authoritative.
    expect(st.activeRuns).toHaveLength(1);
    expect(st.activeRuns[0]?.workflow).toBe(WAVE_WF);
    expect(st.activeRuns[0]?.packageId).toBe(PKG);

    // J (promotion scope): the chore touches ONLY specs/<pkg>/**.
    const show = spawnSync('git', ['-C', sb.fx.root, 'show', '--name-only', '--format=', 'HEAD'], {
      encoding: 'utf8',
    });
    const files = show.stdout.trim().split('\n').filter(Boolean);
    expect(files.length).toBeGreaterThan(0);
    for (const f of files) expect(f.startsWith(`specs/${PKG}/`)).toBe(true);
  });

  it('B: the handoff tick issues no provider dispatch other than the wave launch itself', () => {
    const sb = handoffSandbox('handoff-zeroai');
    tick(sb, ['--once'], {
      getMap: { 'boot-1': { id: 'boot-1', status: 'completed', working_path: sb.wtDir } },
    });
    const log = archonLog(sb);
    // Every logged invocation is an archon lifecycle command; none is a
    // provider dispatch (those would appear as workflow run/implement nodes).
    expect(log).not.toMatch(/implement/i);
    expect(log).toMatch(new RegExp(`^workflow run ${WAVE_WF}`, 'm'));
  });
});

// ── F: legacy preservation ───────────────────────────────────────────────────
describe('legacy preservation (F)', () => {
  it('a completed OPTIMIZED run without a merged PR still raises the recoverable anomaly — the handoff classification keys strictly on the bootstrap workflow identity', () => {
    // (The OFF/CANARY selector lanes themselves are pinned by
    // sharded-wave-rollout.spec.ts and the admission module's non-wave verdict
    // tests; the rollout constant is a frozen commit-gated value with no env
    // override, so here we pin exactly what the handoff could have broken:
    // completion handling of NON-bootstrap workflows.)
    const sb = makeSandbox('legacy-anomaly', 'RUNNING');
    installStub();
    seedState(sb, [{ ...bootstrapEntry(), workflow: OPTIMIZED_WF, runId: 'opt-1' }]);
    const r = tick(sb, ['--once'], { getMap: { 'opt-1': { id: 'opt-1', status: 'completed' } } });
    expect(r.status).toBe(0);
    const events = readState(sb).history.map((h: { event: string }) => h.event);
    expect(events).toContain('anomaly_completed_without_merge');
    expect(events).not.toContain('planning_handoff_complete');
    expect(events).not.toContain('planning_handoff_wave_adopted');
  });
});

// ── G/H/I: duplicate, crash, and stale-row safety ────────────────────────────
describe('handoff state-machine safety (G: duplicate tick · H: crash-after-launch · I: stale rows)', () => {
  const waveRow = {
    id: 'wave-1',
    workflow_name: WAVE_WF,
    user_message: PKG,
    status: 'running',
    started_at: new Date().toISOString(),
  };

  it('G: the tick after a detached wave launch discovers the run instead of launching again (exactly one implementation execution)', () => {
    const sb = makeSandbox('dup-tick', 'RUNNING');
    installStub();
    seedState(sb, [bootstrapEntry()]);
    // Tick 1: handoff fires; ack carries NO run id → awaitingDiscovery.
    tick(sb, ['--once'], {
      getMap: { 'boot-1': { id: 'boot-1', status: 'completed', working_path: sb.wtDir } },
    });
    let st = readState(sb);
    expect(st.activeRuns[0]?.awaitingDiscovery).toBe(true);
    // Tick 2 (duplicate supervisor pass over the handoff window): the runs
    // table now shows the wave row — discovery must ADOPT it.
    tick(sb, ['--once'], { rows: [waveRow] });
    st = readState(sb);
    expect(st.activeRuns[0]?.runId).toBe('wave-1');
    expect(st.activeRuns[0]?.awaitingDiscovery).toBe(false);
    const launches = archonLog(sb)
      .split('\n')
      .filter((l) => l.includes('--detach'))
      .filter((l) => l.includes(PKG));
    expect(launches).toHaveLength(1);
  });

  it('H: a crash after the wave launch but before state persistence replays into ADOPTION — still exactly one run', () => {
    const sb = makeSandbox('crash-replay', 'RUNNING');
    installStub();
    // Pre-crash durable state still tracks the OLD bootstrap entry; origin'
    // runs table proves the wave was already launched before the crash.
    seedState(sb, [bootstrapEntry()]);
    const r = tick(sb, ['--once'], {
      getMap: { 'boot-1': { id: 'boot-1', status: 'completed', working_path: sb.wtDir } },
      rows: [waveRow],
    });
    expect(r.status).toBe(0);
    const events = readState(sb).history.map((h: { event: string }) => h.event);
    expect(events).toContain('planning_handoff_wave_adopted');
    expect(events).not.toContain('planning_handoff_complete');
    const st = readState(sb);
    expect(st.activeRuns).toHaveLength(1);
    expect(st.activeRuns[0]).toMatchObject({ workflow: WAVE_WF, runId: 'wave-1' });
    expect(archonLog(sb)).not.toContain(`run ${WAVE_WF} --detach`);
  });

  it('I: a completed bootstrap row lingering in the runs table can never be adopted or relaunched after the wave becomes authoritative', () => {
    const sb = makeSandbox('stale-row', 'RUNNING');
    installStub();
    seedState(sb, [bootstrapEntry()]);
    const staleBootstrapRow = {
      id: 'boot-1',
      workflow_name: BOOTSTRAP_WF,
      user_message: PKG,
      status: 'running', // even a LIVE-looking stale row must not win
      started_at: new Date().toISOString(),
    };
    const r = tick(sb, ['--once'], {
      getMap: { 'boot-1': { id: 'boot-1', status: 'completed', working_path: sb.wtDir } },
      rows: [staleBootstrapRow, waveRow],
    });
    expect(r.status).toBe(0);
    const st = readState(sb);
    expect(st.activeRuns).toHaveLength(1);
    expect(st.activeRuns[0]).toMatchObject({ workflow: WAVE_WF, runId: 'wave-1' });
    expect(st.history.map((h: { event: string }) => h.event)).toContain(
      'planning_handoff_wave_adopted',
    );
    // No second bootstrap launch ever happened.
    expect(archonLog(sb)).not.toContain(`run ${BOOTSTRAP_WF} --detach`);
  });
});

// ── J: operator seeding CLI (promotion reuse + idempotence + refusal) ────────
describe('--seed-package-planning (J: useful work preserved, promotion is scoped + idempotent)', () => {
  function seedCli(sb: Sandbox) {
    return spawnSync(
      process.execPath,
      [AUTOPILOT, '--seed-package-planning', PKG, '--from', sb.wtDir],
      {
        cwd: sb.fx.root,
        encoding: 'utf8',
        env: {
          ...process.env,
          FORESIFT_AUTOPILOT_REPO: sb.fx.root,
          FORESIFT_AUTOPILOT_STATE_DIR: sb.stateDir,
          GIT_AUTHOR_NAME: 't',
          GIT_COMMITTER_NAME: 't',
          GIT_AUTHOR_EMAIL: 't@t',
          GIT_COMMITTER_EMAIL: 't@t',
          GIT_CONFIG_GLOBAL: '/dev/null',
          GIT_CONFIG_SYSTEM: '/dev/null',
        },
      },
    );
  }

  it('copies only specs/<pkg>/** into main as a chore; a second run is a no-op; the package branch is untouched', () => {
    const sb = makeSandbox('seed-cli', 'RUNNING');
    // A package branch carrying useful implementation work — the promotion
    // must not move it.
    sb.fx.g(['switch', '-q', '-c', `foresift/${PKG}`]);
    sb.fx.writeFile('packages/a/src/alpha.ts', 'export const alpha = 1;\n');
    sb.fx.commitAll('feat(a): useful implementation slice');
    const branchSha = spawnSync('git', ['-C', sb.fx.root, 'rev-parse', 'HEAD'], {
      encoding: 'utf8',
    }).stdout;
    sb.fx.g(['switch', '-q', 'main']);

    const r1 = seedCli(sb);
    expect(r1.status).toBe(0);
    const res1 = JSON.parse(r1.stdout);
    expect(res1.ok).toBe(true);
    expect(res1.promoted).toBe(true);
    expect(existsSync(join(sb.fx.root, 'specs', PKG, 'tasks.md'))).toBe(true);
    const show = spawnSync('git', ['-C', sb.fx.root, 'show', '--name-only', '--format=', 'HEAD'], {
      encoding: 'utf8',
    }).stdout;
    for (const f of show.trim().split('\n').filter(Boolean))
      expect(f.startsWith(`specs/${PKG}/`)).toBe(true);

    const r2 = seedCli(sb);
    expect(r2.status).toBe(0);
    expect(JSON.parse(r2.stdout)).toMatchObject({ ok: true, promoted: false });

    const shaAfter = spawnSync('git', ['-C', sb.fx.root, 'rev-parse', `foresift/${PKG}`], {
      encoding: 'utf8',
    }).stdout;
    expect(shaAfter).toBe(branchSha);
  });

  it('refuses when the main checkout has uncommitted state under specs/<pkg>', () => {
    const sb = makeSandbox('seed-dirty', 'RUNNING');
    writePlannedTree(sb.fx.root); // uncommitted planning truth on main side
    const r = seedCli(sb);
    expect(r.status).toBe(1);
    expect(JSON.parse(r.stdout).refused).toMatch(/uncommitted changes under specs/);
  });
});
