import { describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import {
  OPTIMIZED_WORKFLOW,
  PLANNING_BOOTSTRAP_WORKFLOW,
  WAVE_WORKFLOW,
  admitWorkflowForLaunch,
} from '../../scripts/automation/wave-admission.mjs';

const SCRIPT = resolve(import.meta.dirname, '../../scripts/automation/package-plan-complete.mjs');

const SPEC = [
  '# pkg-x scoped specification',
  '',
  'Subordinate to the PRD; binds FR-X-001 and FR-X-002 with acceptance',
  'criteria and test references. No unresolved markers.',
  '',
].join('\n');

const PLAN = [
  '# pkg-x implementation plan',
  '',
  'Architecture, approach, and trade-offs for FR-X-001 / FR-X-002 delivery.',
  'Generated by the scoped planner; complete and traceable.',
  '',
].join('\n');

const TASKS = [
  '- [x] T101 Groundwork for `packages/x/src/base.ts`. Traces: FR-X-001.',
  '- [ ] T102 Implement alpha in `packages/x/src/alpha.ts`. Traces: FR-X-001, FR-X-002.',
  '',
].join('\n');

/** Hermetic repo root carrying one PLANNED package (pkg-x) and one UNPLANNED (pkg-y). */
function buildFixture(): string {
  const root = mkdtempSync(join(tmpdir(), 'wave-admit-fx-'));
  mkdirSync(join(root, 'specs', 'pkg-x'), { recursive: true });
  mkdirSync(join(root, 'specs', 'implementation'), { recursive: true });
  writeFileSync(join(root, 'specs', 'pkg-x', 'spec.md'), SPEC);
  writeFileSync(join(root, 'specs', 'pkg-x', 'plan.md'), PLAN);
  writeFileSync(join(root, 'specs', 'pkg-x', 'tasks.md'), TASKS);
  const ms = {
    schemaVersion: '1.0.0',
    milestoneId: 'MX',
    status: 'ACTIVE',
    packages: [
      {
        id: 'pkg-x',
        objective: 'Implement subsystem x end to end with full evidence coverage.',
        requirementIds: ['FR-X-001', 'FR-X-002'],
        dependencies: [],
        risk: 'MEDIUM',
        parallelizable: false,
        writeScopes: ['packages/x/**'],
        verificationCommands: ['pnpm test'],
        status: 'RUNNING',
      },
      {
        id: 'pkg-y',
        objective: 'Implement independent subsystem y behind its own boundary.',
        requirementIds: ['FR-Y-001'],
        dependencies: [],
        risk: 'LOW',
        parallelizable: true,
        writeScopes: ['packages/y/**'],
        verificationCommands: ['pnpm test'],
        status: 'PENDING',
      },
    ],
  };
  writeFileSync(
    join(root, 'specs', 'implementation', 'current-milestone.json'),
    JSON.stringify(ms),
  );
  return root;
}

function runPlanComplete(pkg: string, root: string, extra: string[] = []) {
  // NOTE: --repo-only is intentionally the LAST argument in this base argv —
  // it pins the trailing-bare-flag parsing contract.
  return spawnSync(process.execPath, [SCRIPT, '--package', pkg, '--root', root, ...extra], {
    encoding: 'utf8',
  });
}

describe('wave-admission — launch-seam gate for the implementation-only sharded wave (defect #18)', () => {
  describe('pure admission decision', () => {
    it('admits a wave-routed package whose planning completeness is proven', () => {
      expect(admitWorkflowForLaunch(WAVE_WORKFLOW, true)).toBe(WAVE_WORKFLOW);
    });

    it('demotes a wave-routed package with unproven planning to the PLANNING-ONLY bootstrap', () => {
      // Planned-handoff law: the demotion target is the bounded planning-only
      // bootstrap (zero implementation nodes), NOT the full optimized
      // topology — an unplanned-origin package must never continue into
      // optimized implementation after its planning bootstrap completes.
      expect(admitWorkflowForLaunch(WAVE_WORKFLOW, false)).toBe(PLANNING_BOOTSTRAP_WORKFLOW);
      // "could not evaluate" must fail closed toward planning, never toward the wave
      expect(admitWorkflowForLaunch(WAVE_WORKFLOW, null as unknown as boolean)).toBe(
        PLANNING_BOOTSTRAP_WORKFLOW,
      );
      expect(admitWorkflowForLaunch(WAVE_WORKFLOW, undefined as unknown as boolean)).toBe(
        PLANNING_BOOTSTRAP_WORKFLOW,
      );
    });

    it('never touches non-wave selector verdicts (legacy lane, optimized-under-OFF)', () => {
      expect(admitWorkflowForLaunch('foresift-work-package', false)).toBe('foresift-work-package');
      expect(admitWorkflowForLaunch(OPTIMIZED_WORKFLOW, false)).toBe(OPTIMIZED_WORKFLOW);
      expect(admitWorkflowForLaunch(OPTIMIZED_WORKFLOW, true)).toBe(OPTIMIZED_WORKFLOW);
    });
  });

  describe('package-plan-complete.mjs --repo-only (supervisor probe mode)', () => {
    it('reports a planned package complete without any artifacts dir', () => {
      const root = buildFixture();
      const r = runPlanComplete('pkg-x', root, ['--repo-only']);
      expect(r.status).toBe(0);
      expect(JSON.parse(r.stdout!).complete).toBe(true);
    });

    it('reports an unplanned package incomplete with precise reasons', () => {
      const root = buildFixture();
      const r = runPlanComplete('pkg-y', root, ['--repo-only']);
      expect(r.status).toBe(1);
      const out = JSON.parse(r.stdout!);
      expect(out.complete).toBe(false);
      expect(out.errors.join(' ')).toContain('missing specs/pkg-y/spec.md');
      expect(out.errors.join(' ')).toContain('missing specs/pkg-y/tasks.md');
    });

    it('keeps placeholder/marker scanning active in repo-only mode', () => {
      const root = buildFixture();
      // Otherwise-complete planned package gains one unresolved marker.
      writeFileSync(
        join(root, 'specs', 'pkg-x', 'tasks.md'),
        TASKS + '- [x] T103 TODO pick cache\n',
      );
      const r = runPlanComplete('pkg-x', root, ['--repo-only']);
      expect(r.status).toBe(1);
      expect(JSON.parse(r.stdout!).errors.join(' ')).toMatch(/placeholder.*tasks\.md|tasks\.md/);
    });

    it('refuses the default mode without an artifacts dir — repo-only stays opt-in', () => {
      const root = buildFixture();
      const r = spawnSync(process.execPath, [SCRIPT, '--package', 'pkg-x', '--root', root], {
        encoding: 'utf8',
      });
      expect(r.status).toBe(1);
      expect(r.stdout).toContain('--repo-only');
    });
  });
});
