#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import {
  buildArtifacts,
  checkArtifacts,
  canonicalJson,
} from '../generate-requirement-manifest/cli.mjs';

const sha = (text) => `sha256:${createHash('sha256').update(text, 'utf8').digest('hex')}`;
const cleanRef = (reference) =>
  (reference.split(/\s+@(?:requirement|acceptance)\s+/, 1)[0] ?? reference).replace(/\/$/, '/**');
function matcher(pattern) {
  const escaped = pattern
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replaceAll('**', '\0')
    .replaceAll('*', '[^/]*')
    .replaceAll('\0', '.*');
  return new RegExp(`^${escaped}$`);
}
async function allFiles(rootDir) {
  const output = [];
  const walk = async (relative) => {
    let entries;
    try {
      entries = await readdir(path.join(rootDir, relative), { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (
        entry.name === '.git' ||
        entry.name === 'node_modules' ||
        entry.name === 'test' ||
        entry.name === '__tests__'
      )
        continue;
      const child = path.posix.join(relative, entry.name);
      if (entry.isDirectory()) await walk(child);
      else output.push(child);
    }
  };
  await walk('');
  return output.sort();
}
function finding(requirement, rule, targetPath, message) {
  return { requirement, requirementId: requirement, rule, path: targetPath, message };
}

export async function verifyTree(rootDir = process.cwd()) {
  const manifest = JSON.parse(
    await readFile(
      path.join(
        rootDir,
        'docs/spec/crypto_intelligence_agent_gateway_PRD_FINAL_v6.0.requirements.json',
      ),
      'utf8',
    ),
  );
  const milestone = JSON.parse(
    await readFile(path.join(rootDir, 'specs/implementation/current-milestone.json'), 'utf8'),
  );
  const files = await allFiles(rootDir);
  const findings = [];
  const active = milestone.status === 'ACTIVE' ? milestone.milestoneId : undefined;
  for (const item of manifest.requirements) {
    if (!item.owner || !item.implementationRefs?.length || !item.testRefs?.length)
      findings.push(
        finding(
          item.id,
          'NORMATIVE_MAPPING_REQUIRED',
          `manifest:${item.id}`,
          'owner, implementation, and tests are required',
        ),
      );
    for (const reference of item.implementationRefs ?? []) {
      const pattern = cleanRef(reference);
      const matches = files.filter((file) => matcher(pattern).test(file));
      if (item.dependencyGroup === active && matches.length === 0)
        findings.push(
          finding(
            item.id,
            'ACTIVE_IMPLEMENTATION_PATH_MISSING',
            pattern,
            'active implementationRef resolves to no code path',
          ),
        );
      if (item.dependencyGroup !== active) {
        for (const file of matches) {
          if ((await readFile(path.join(rootDir, file), 'utf8')).includes(item.id))
            findings.push(
              finding(
                item.id,
                'DEPENDENCY_GATE_CLOSED',
                file,
                `${item.dependencyGroup} is not active`,
              ),
            );
        }
      }
    }
  }
  const generated = await buildArtifacts(rootDir);
  for (const difference of await checkArtifacts(rootDir, generated))
    findings.push(
      finding('FR-TRACE-003', 'GENERATED_DOCUMENT_DRIFT', difference, 'generated bytes differ'),
    );

  const exceptions = JSON.parse(
    await readFile(
      path.join(rootDir, 'packages/release-conformance/src/orphan-exceptions.json'),
      'utf8',
    ),
  );
  const mapped = manifest.requirements.flatMap((item) =>
    item.implementationRefs.map((ref) => matcher(cleanRef(ref))),
  );
  const exempt = exceptions.map((entry) => matcher(entry.pattern));
  for (const file of files.filter((name) =>
    /^(?:apps|packages)\/.+\/src\/.+\.(?:ts|tsx|js|mjs|cjs)$/.test(name),
  )) {
    if (!mapped.some((regex) => regex.test(file)) && !exempt.some((regex) => regex.test(file)))
      findings.push(
        finding(
          'FR-TRACE-003',
          'ORPHAN_PRODUCT_SOURCE',
          file,
          'no implementationRef or traced exception matches',
        ),
      );
  }

  // Construct and immediately content-verify the live release projection.
  const lock = await readFile(path.join(rootDir, 'pnpm-lock.yaml'), 'utf8');
  const audit = JSON.parse(
    await readFile(
      path.join(rootDir, 'docs/spec/crypto_intelligence_agent_gateway_PRD_FINAL_v6.0.audit.json'),
      'utf8',
    ),
  );
  if (manifest.document.normalizedSha256 !== audit.hashes.documentNormalizedSha256)
    findings.push(
      finding(
        'FR-TRACE-006',
        'RELEASE_REPORT_HASH_MISMATCH',
        'docs/spec',
        'normalized manifest/audit provenance differs',
      ),
    );
  const reportBody = {
    schema: 'foresift/release-conformance-report@1',
    documentHash: `sha256:${audit.hashes.documentArtifactSha256}`,
    normalizedDocumentHash: `sha256:${manifest.document.normalizedSha256}`,
    manifestHash: `sha256:${audit.hashes.requirementManifestSha256}`,
    normalizedHashConsistency: 'CONSISTENT',
    migrationHashes: {},
    schemaHashes: {},
    sbomHash: sha(lock),
    dependencyHash: sha(lock),
    conformanceResults: findings,
    unresolvedDeviations: exceptions,
    activationState: { [milestone.milestoneId]: milestone.status },
    rollbackTarget: 'previous-approved-report:required-before-activation',
  };
  const report = { ...reportBody, reportId: sha(canonicalJson(reportBody)) };
  const { reportId, ...verifyBody } = report;
  if (reportId !== sha(canonicalJson(verifyBody)))
    findings.push(
      finding(
        'FR-TRACE-006',
        'RELEASE_REPORT_HASH_MISMATCH',
        'release-report',
        'content address differs',
      ),
    );
  findings.sort(
    (a, b) =>
      a.requirement.localeCompare(b.requirement) ||
      a.rule.localeCompare(b.rule) ||
      a.path.localeCompare(b.path),
  );
  return { ok: findings.length === 0, findings, reportId };
}

const result = await verifyTree(
  process.env.FORESIFT_ROOT ? path.resolve(process.env.FORESIFT_ROOT) : process.cwd(),
).catch((error) => ({
  ok: false,
  findings: [
    finding(
      'FR-TRACE-003',
      'VERIFIER_REFUSED',
      'repository',
      error instanceof Error ? error.message : String(error),
    ),
  ],
}));
process.stdout.write(`${JSON.stringify(result)}\n`);
if (!result.ok) process.exitCode = 1;
