/**
 * Recall Estimator & Claim-Basis Truth Table (FR-DISC-006, FR-DISC-010, §63.9).
 * Normative text:
 * FR-DISC-006: "Retrospective or prospective independent-universe enumeration estimates discovery
 * recall without relying only on the same upstream lineage as live aggregate discovery."
 * FR-DISC-010: "Recall or missed-gem claims require independent first-party observation, independent provider
 * lineage, or valid known inclusion probabilities; a universe generated by the evaluated source cannot establish its own recall."
 */
import { describe, expect, it } from 'bun:test';
import {
  RECALL_VECTOR_INDEPENDENT_FIRST_PARTY,
  RECALL_VECTOR_INDEPENDENT_LINEAGE,
  RECALL_VECTOR_VALID_INCLUSION_PROBABILITIES,
  RECALL_VECTOR_SHARED_LINEAGE_TRAP,
  RECALL_VECTOR_SELF_RECALL_TRAP,
  RECALL_VECTOR_NO_BASIS_TRAP,
  type RecallSampleVector,
  type RecallVerdict,
} from '../../../tests/fixtures/disc/recall-samples.ts';

interface RecallEvaluationOutput {
  verdict: RecallVerdict;
  independent: boolean;
  classification: string;
  allowedInHistoricalDecisionBundle: boolean;
  refusalReason?: string;
}

function evaluateRecallClaim(sample: RecallSampleVector): RecallEvaluationOutput {
  // (§63.9) Retrospective existence/outcome evidence NEVER enters historical decision bundle
  const allowedInHistoricalDecisionBundle = false;

  // 1. Self-recall trap: evaluated source generated the universe
  if (sample.selfGeneratedUniverse || sample.evaluatedSourceId === sample.universeSourceId) {
    return {
      verdict: 'SELF_RECALL_REFUSED',
      independent: false,
      classification: 'SELF_RECALL_REFUSED',
      allowedInHistoricalDecisionBundle,
      refusalReason: 'A universe generated by the evaluated source cannot establish its own recall (FR-DISC-010)',
    };
  }

  // 2. No-basis trap: missing valid claim basis or unverified universe
  if (sample.claimBasis === 'NO_BASIS_TRAP' || !sample.groundTruthExists) {
    return {
      verdict: 'NO_BASIS_REFUSED',
      independent: false,
      classification: 'NO_BASIS_REFUSED',
      allowedInHistoricalDecisionBundle,
      refusalReason: 'Claim lacks sound basis: no independent observation or inclusion probabilities (FR-DISC-010)',
    };
  }

  // 3. Shared-lineage trap: upstream lineage shared with evaluated source
  if (sample.sharedLineageWithEvaluated || sample.claimBasis === 'SHARED_LINEAGE_TRAP') {
    return {
      verdict: 'DEPENDENT_LINEAGE_DISCLOSED',
      independent: false,
      classification: sample.discoveredByEvaluatedSource ? 'DISCOVERED' : 'LINEAGE_DEPENDENT',
      allowedInHistoricalDecisionBundle,
      refusalReason: 'Upstream lineage shared with live discovery; dependency disclosed (FR-DISC-006)',
    };
  }

  // 4. Valid independent recall basis
  const classification = sample.discoveredByEvaluatedSource ? 'DISCOVERED' : 'NOT_DISCOVERED';
  return {
    verdict: 'VALID_INDEPENDENT_RECALL',
    independent: true,
    classification,
    allowedInHistoricalDecisionBundle,
  };
}

describe('Recall Estimator & Claim-Basis Truth Table (FR-DISC-006, FR-DISC-010)', () => {
  it('verdict 1: accepts independent first-party observation as valid independent recall basis', () => {
    const output = evaluateRecallClaim(RECALL_VECTOR_INDEPENDENT_FIRST_PARTY);

    expect(output.verdict).toBe('VALID_INDEPENDENT_RECALL');
    expect(output.independent).toBe(true);
    expect(output.classification).toBe('NOT_DISCOVERED');
    expect(output.allowedInHistoricalDecisionBundle).toBe(false);
  });

  it('verdict 1: accepts independent archive lineage as valid independent recall basis', () => {
    const output = evaluateRecallClaim(RECALL_VECTOR_INDEPENDENT_LINEAGE);

    expect(output.verdict).toBe('VALID_INDEPENDENT_RECALL');
    expect(output.independent).toBe(true);
    expect(output.classification).toBe('NOT_DISCOVERED');
  });

  it('verdict 1: accepts valid known inclusion probabilities as valid independent recall basis', () => {
    const output = evaluateRecallClaim(RECALL_VECTOR_VALID_INCLUSION_PROBABILITIES);

    expect(output.verdict).toBe('VALID_INDEPENDENT_RECALL');
    expect(output.independent).toBe(true);
    expect(output.classification).toBe('DISCOVERED');
  });

  it('verdict 2: catches shared-lineage trap, discloses dependency, and refuses independent claim', () => {
    const output = evaluateRecallClaim(RECALL_VECTOR_SHARED_LINEAGE_TRAP);

    expect(output.verdict).toBe('DEPENDENT_LINEAGE_DISCLOSED');
    expect(output.independent).toBe(false);
    expect(output.classification).toBe('LINEAGE_DEPENDENT');
    expect(output.refusalReason).toContain('Upstream lineage shared');
  });

  it('verdict 3: structurally refuses self-recall trap with persisted refusal verdict', () => {
    const output = evaluateRecallClaim(RECALL_VECTOR_SELF_RECALL_TRAP);

    expect(output.verdict).toBe('SELF_RECALL_REFUSED');
    expect(output.independent).toBe(false);
    expect(output.classification).toBe('SELF_RECALL_REFUSED');
    expect(output.refusalReason).toContain('universe generated by the evaluated source');
  });

  it('verdict 4: refuses claims without sound basis or ground-truth existence', () => {
    const output = evaluateRecallClaim(RECALL_VECTOR_NO_BASIS_TRAP);

    expect(output.verdict).toBe('NO_BASIS_REFUSED');
    expect(output.independent).toBe(false);
    expect(output.classification).toBe('NO_BASIS_REFUSED');
    expect(output.refusalReason).toContain('Claim lacks sound basis');
  });

  it('enforces that retrospective evidence never enters historical decision bundles across all vectors', () => {
    const vectors = [
      RECALL_VECTOR_INDEPENDENT_FIRST_PARTY,
      RECALL_VECTOR_INDEPENDENT_LINEAGE,
      RECALL_VECTOR_VALID_INCLUSION_PROBABILITIES,
      RECALL_VECTOR_SHARED_LINEAGE_TRAP,
      RECALL_VECTOR_SELF_RECALL_TRAP,
      RECALL_VECTOR_NO_BASIS_TRAP,
    ];

    for (const vec of vectors) {
      const output = evaluateRecallClaim(vec);
      expect(output.allowedInHistoricalDecisionBundle).toBe(false);
    }
  });
});
